steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: ['run', 'deploy', 'genaiq-flask', 
           '--source', '.', 
           '--region', 'us-central1', 
           '--platform', 'managed']

options:
  logging: CLOUD_LOGGING_ONLY

serviceAccount: 'projects/genaiq/serviceAccounts/genaiq-433814@appspot.gserviceaccount.com'