steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/genaiq/genaiq-flask', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/genaiq/genaiq-flask']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'genaiq-flask', '--image', 'gcr.io/genaiq/genaiq-flask', '--region', 'us-central1', '--platform', 'managed']

images:
  - 'gcr.io/genaiq/genaiq-flask'
